// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarcraftApi.Context;

namespace WarcraftApi.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20210714172003_TilesAdded")]
    partial class TilesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WarcraftApi.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Cash")
                        .HasColumnType("integer");

                    b.Property<int>("Income")
                        .HasColumnType("integer");

                    b.Property<int>("Minions")
                        .HasColumnType("integer");

                    b.Property<int>("Spawner")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WarcraftApi.Entities.Tile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("OwnedById")
                        .HasColumnType("text");

                    b.Property<int>("defence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnedById");

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("WarcraftApi.Entities.Tile", b =>
                {
                    b.HasOne("WarcraftApi.Entities.Player", "OwnedBy")
                        .WithMany()
                        .HasForeignKey("OwnedById");

                    b.Navigation("OwnedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
